############################################
#
#    dolfin.cpp.fem
# https://fenicsproject.org/docs/dolfin/2018.1.0/python/_autogenerated/dolfin.cpp.fem.html
#
#    dolfin.fem module
# https://fenicsproject.org/docs/dolfin/2017.2.0/python/programmers-reference/fem/index.html
#
############################################

@pyclass dolfin LinearVariationalProblem
@pyclass dolfin LinearVariationalSolver
@pyclass dolfin NonlinearVariationalProblem
@pyclass dolfin NonlinearVariationalSolver
@pyclass dolfin LocalSolver
@pyclass dolfin DirichletBC
@pyclass dolfin AutoSubDomain

@pyfunc dolfin assemble
@pyfunc dolfin assemble_system
@pyfunc dolfin errornorm
@pyfunc dolfin project
@pyfunc dolfin solve

export LinearVariationalProblem, LinearVariationalSolver, NonlinearVariationalProblem, 
       NonlinearVariationalSolver, LocalSolver, DirichletBC, AutoSubDomain, assemble, 
       assemble_system, errornorm, project, solve


############################################
#
#    ufl.finiteelement
#
# https://fenicsproject.org/docs/ufl/1.6.0/ufl.finiteelement.html
#
############################################

@pyclass ufl FiniteElementBase
@pyclass ufl FiniteElement FiniteElementBase

@pyclass ufl MixedElement FiniteElementBase
@pyclass ufl VectorElement MixedElement
@pyclass ufl TensorElement MixedElement

@pyclass ufl EnrichedElement FiniteElementBase
@pyclass ufl RestrictedElement FiniteElementBase
@pyclass ufl TensorProductElement FiniteElementBase

# OuterProductElement:  no need to export
# OuterProductElement:  not exported in `ufl`
@pyclass ufl OuterProductElement FiniteElementBase

# 暂时没搞懂，先注释掉
#@pyclass ufl HDiv OuterProductElement
#@pyclass ufl HCurl OuterProductElement

# no need to export
# not exported in `ufl`
@pyclass ufl OuterProductVectorElement MixedElement
@pyclass ufl TraceElement FiniteElementBase

@pyclass ufl BrokenElement FiniteElementBase

@pyfunc ufl FacetElement
@pyfunc ufl InteriorElement

*(fe1::FiniteElementBase, fe2::FiniteElementBase) = FiniteElementBase(fe1.pyobject * fe2.pyobject)

export FiniteElementBase, FiniteElement, MixedElement, VectorElement, TensorElement, EnrichedElement,
        RestrictedElement, TensorProductElement, BrokenElement, FacetElement, InteriorElement


############################################
#
#    dolfin.cpp.adaptivity
#
# https://fenicsproject.org/docs/dolfin/2018.1.0/python/_autogenerated/dolfin.cpp.adaptivity.html?highlight=timeseries#dolfin.cpp.adaptivity.TimeSeries
#
############################################

# no need to export
# not exported in `dolfin` or `ufl`
@pyclass dolfin GoalFunctional Form
@pyclass dolfin ErrorControl Variable
@pyclass dolfin GenericAdaptiveVariationalSolver Variable

@pyclass dolfin TimeSeries Variable
@pyclass dolfin AdaptiveLinearVariationalSolver GenericAdaptiveVariationalSolver
@pyclass dolfin AdaptiveNonlinearVariationalSolver GenericAdaptiveVariationalSolver

export TimeSeries, AdaptiveLinearVariationalSolver, AdaptiveNonlinearVariationalSolver 



