
############################################
#
#    dolfin.cpp.io module
#
# https://fenicsproject.org/docs/dolfin/2018.1.0/python/_autogenerated/dolfin.cpp.io.html
#
############################################

@pyclass dolfin File
@pyclass dolfin XDMFFile

<<(file::File, u::Mesh) =  file.pyobject << u.pyobject
<<(file::File, u::FeFunction) =  file.pyobject << u.pyobject
<<(file::File, u::Tuple{FeFunction,Real}) =  file.pyobject <<  (u[1].pyobject, u[2])

export File, XDMFFile


