############################################
#
#    dolfin.mesh
#    dolfin.cpp.mesh module
#    dolfin.cpp.generation
#
# https://fenicsproject.org/docs/dolfin/2018.1.0/python/_autogenerated/dolfin.cpp.mesh.html
# https://fenicsproject.org/docs/dolfin/2017.2.0/python/programmers-reference/cpp/mesh/index.html
# https://fenicsproject.org/docs/dolfin/latest/python/_autogenerated/dolfin.cpp.generation.html
#
############################################

@pyclass dolfin MeshValueCollection
@pyclass dolfin MeshFunction
@pyclass dolfin UnitTriangleMesh
@pyclass dolfin SphericalShellMesh
@pyclass dolfin UnitDiscMesh
@pyclass dolfin MeshColoring

@pyclass dolfin MeshEditor
@pyclass dolfin MeshGeometry
@pyclass dolfin MeshPartitioning
@pyclass dolfin MeshQuality
@pyclass dolfin MeshTransformation
@pyclass dolfin CellType
@pyclass dolfin PeriodicBoundaryComputation
@pyclass dolfin SubsetIterator

@pyclass dolfin SubDomain
@pyclass dolfin DomainBoundary SubDomain

@pyclass dolfin Mesh
@pyclass dolfin SubMesh Mesh
@pyclass dolfin BoundaryMesh Mesh
@pyclass dolfin BoxMesh Mesh
@pyclass dolfin UnitCubeMesh BoxMesh
@pyclass dolfin IntervalMesh Mesh
@pyclass dolfin UnitIntervalMesh IntervalMesh
@pyclass dolfin RectangleMesh Mesh
@pyclass dolfin UnitSquareMesh RectangleMesh

@pyclass dolfin MeshEntity
@pyclass dolfin Cell MeshEntity
@pyclass dolfin Edge MeshEntity
@pyclass dolfin Face MeshEntity
@pyclass dolfin Facet MeshEntity
@pyclass dolfin Vertex MeshEntity

@pyclass dolfin MeshTopology
@pyclass dolfin MultiMesh
@pyclass dolfin CompiledSubDomain

@pyfunc dolfin cells
@pyfunc dolfin edges
@pyfunc dolfin entities
@pyfunc dolfin faces
@pyfunc dolfin facets
@pyfunc dolfin vertices

export MeshValueCollection, MeshFunction, UnitTriangleMesh, SphericalShellMesh, UnitDiscMesh, 
           MeshColoring, MeshEditor, MeshGeometry, MeshPartitioning, MeshQuality, MeshTransformation, 
           CellType, PeriodicBoundaryComputation,  SubsetIterator, SubDomain, DomainBoundary, Mesh, 
           SubMesh, BoundaryMesh, BoxMesh, UnitCubeMesh, IntervalMesh, UnitIntervalMesh, RectangleMesh, 
           UnitSquareMesh, MeshEntity, Cell, Edge, Face, Facet, Vertex, MeshTopology, MultiMesh, 
           CompiledSubDomain, cells, edges, entities, faces, facets, vertices


